name: open_music_player
description: Open Music Player - Cross-platform music player client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  go_router: ^13.2.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
